### ISSUE TITLE
batphish.bat

### ISSUE THREAD

**Issue by gmnabil** [pranavbhuchhada/batphish#1]
If type batphish.bat + Enter no run....

**Comment by pranavbhuchhada** [comment]
Hey @gmnabil Can you please elaborate what you are trying to say?

**Comment by pranavbhuchhada** [comment]
> If type batphish.bat + Enter no run....

Hey @gmnabil can you please elaborate your issue or suggetion?

**Comment by gmnabil** [comment]
how run this tools.. I trying to type "batphish.bat" but no work, I trying to "sh batphish.bat" no work... I trying  to "python
batphish.bat"
how run this tools...plz give me demo short.

**Comment by pranavbhuchhada** [comment]
> how run this tools.. I trying to type "batphish.bat" but no work, I trying to "sh batphish.bat" no work... I trying to "python
> batphish.bat"
> how run this tools...plz give me demo short.

Hey @gmnabil for sake of clarification this is not a shell-script, It's a bat-script which will only work in windows environment.
You can run this script by simply typing `batphish.bat` (considering you are same directory as the file) in windows command prompt.
